FROM mcr.microsoft.com/dotnet/sdk:6.0 AS sdk
WORKDIR /app

COPY ./ ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=sdk /app/out ./

ENV ConnectionString="Server=mysql2019,1433;Database=Pluto;User Id=sa;Password=Password123;"

ENTRYPOINT ["dotnet", "api_demo.dll"]